version = 2

[linters]
enable = [
  "errcheck",
  "govet",
  "ineffassign",
  "staticcheck",
  "unused",
  "gosimple",
  "goimports",
]

[run]
concurrency = 4
timeout = "10m"

[linters-settings.goimports]
local-prefixes = "github.com/gardener/etcd-steward"

[issues]
exclude-use-default = false
