# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

FROM gcr.io/distroless/static-debian12:nonroot

COPY bin/etcd-steward-linux /etcd-steward

ENTRYPOINT ["/etcd-steward"]
